version: "3.9"
services:
  web-next-dev:
    image: "next-dev"
    restart: always

    volumes:
        - ../../next/:/usr/app
    
    depends_on:
      - mongo-dev
    environment:
      WAIT_HOSTS: mongo-dev:27017
      WAIT_HOSTS_TIMEOUT: 120

    links:
      - "mongo-dev:mongo-dev"

  mongo-dev:
    image: mongo
    command: [--auth]
    restart: always

    ports: 
      - "3000:3000"

    environment:
      MONGO_INITDB_ROOT_USERNAME: /run/secrets/mongo_root_user
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongo_root_pass
    volumes:
      - ../../initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ../../mongo/data:/data/db
    secrets:
      - mongo_root_user
      - mongo_root_pass

  

secrets:
  mongo_root_user:
    file: ../../mongo/auth/root/user
  mongo_root_pass:
    file: ../../mongo/auth/root/pass

