version: "3.9"
services:
  web-next-dev:
    image: "next-dev"
    restart: always

    ports:
      - "3000:3000"

    volumes:
      - ../../next/:/usr/app

    depends_on:
      - mongo-dev
      - redis-dev
    environment:
      WAIT_HOSTS: mongo-dev:27017
      WAIT_HOSTS_TIMEOUT: 120

    links:
      - "mongo-dev:db"
      - "redis-dev:redis"

  mongo-dev:
    image: mongo
    command: [--auth]
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: /run/secrets/mongo_root_user
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongo_root_pass
    volumes:
      - ../../initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ../../mongo/data:/data/db
    secrets:
      - mongo_root_user
      - mongo_root_pass

  redis-dev:
    image: "redis:6.2.5-alpine"
    ports:
      - "6379:6379"

secrets:
  mongo_root_user:
    file: ../../mongo/auth/root/user
  mongo_root_pass:
    file: ../../mongo/auth/root/pass
