version: "3.9"
services:
  web-next-prod:
    image: "next-prod"
    restart: always

    depends_on:
      - mongo-prod

    env_file:
      - ../../next/.env.local

    environment:
      WAIT_HOSTS: mongo-prod:27017
      WAIT_HOSTS_TIMEOUT: 120

    volumes:
      - ../../mongo/dataFromOldServer:/data/dataFromOldServer

    links:
      - "mongo-prod:db"
      - "redis-prod:redis"

  mongo-prod:
    image: mongo
    command: [--auth]
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: /run/secrets/mongo_root_user
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongo_root_pass
    volumes:
      - ../../initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ../../mongo/data:/data/db
    secrets:
      - mongo_root_user
      - mongo_root_pass

  redis-prod:
    image: "redis:6.2.5-alpine"

  nginx-prod:
    image: nginx:latest
    restart: always
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/

    links:
      - "web-next-prod:next"

    ports:
      - 3000:80
      - 3001:443

secrets:
  mongo_root_user:
    file: ../../mongo/auth/root/user
  mongo_root_pass:
    file: ../../mongo/auth/root/pass
